In [4]:
import numpy as np
from numpy import nan
X = np.array([[ nan, 0, 3 ],
[ 3, 7, 9 ],
[ 3, 5, 2 ],
[ 4, nan, 6 ],
[ 8, 8, 1 ]])

In [5]:
X

array([[ nan,   0.,   3.],
       [  3.,   7.,   9.],
       [  3.,   5.,   2.],
       [  4.,  nan,   6.],
       [  8.,   8.,   1.]])

In [6]:
from sklearn.preprocessing import Imputer
imp = Imputer(strategy='mean')
X2 = imp.fit_transform(X)
X2

array([[ 4.5,  0. ,  3. ],
       [ 3. ,  7. ,  9. ],
       [ 3. ,  5. ,  2. ],
       [ 4. ,  5. ,  6. ],
       [ 8. ,  8. ,  1. ]])

In [15]:
import numpy as np
from numpy import nan
X = np.array([[ nan, nan, nan ],
[ 3, nan, 9 ],
[ 3, nan, 2 ],
[ 4, nan, 6 ],
[ 8, nan, 1 ]])
X.mean()

nan

In [14]:
X.isnull().values.any()

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'

In [11]:
from sklearn.preprocessing import Imputer
imp = Imputer(strategy='mean')
X2 = imp.fit_transform(X)
X2

array([[ 4.5,  4.5],
       [ 3. ,  9. ],
       [ 3. ,  2. ],
       [ 4. ,  6. ],
       [ 8. ,  1. ]])

In [12]:
print(X.isnull().sum())

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'